(define code
  (list
    (@ #x0000)
    (% 'resets)
    (.jmp (%a 'begin))
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)

    (@ #x34)
    (% 'begin)
    (.sbi (&ddrc) 5)

    (% 'loop)
    (.sbi (&portc) 5)
    (.rjmp 0)
    (.cbi (&portc) 5)
    (.rjmp (%r 'loop))))

(define (cu)
  (load "test/avr-test.ss")
  (avr16-compile-and-upload code))
