(define code
  (list
    (@ #x0000)
    (% 'resets)
    (jmp. 'begin)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)
    (nop.) (nop.)

    (@ #x34)
    (% 'begin)
    (sbi. (^sram &ddrc) 5)

    (% 'loop)
    (sbi. (^sram &portc) 5)
    (rjmp. 0)
    (rjmp. 0)
    (cbi. (^sram &portc) 5)
    (rjmp. 'loop)))

(define (cu)
  (load "test/avr-test.ss")
  (avr16-compile-and-upload code))
