(include "avr.ss")

(define code
  (list
    (@ #x0000)
    (% 'resets)
    (.jmp (%a 'begin))
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)
    (.nop) (.nop)

    (@ #x34)
    (% 'begin)
    (.sbi (&ddrc) (&ddrc 5))

    (% 'loop)
    (.sbi (&portc) (&portc 5))
    (.rjmp 0)
    (.cbi (&portc) (&portc 5))
    (.rjmp (%r 'loop))))

(define (save)
  (call-with-output-file "avr_test.hex"
    (lambda (file)
      (display (avr16-compile code) file))))
