#!/usr/bin/env sh

# compile to c
gambitc -o obj -c uo.ss || exit
gambitc -o obj -c avr.ss || exit

# generate link file
gambitc -link -flat -o obj/avr.o1.c obj/uo.c obj/avr.c || exit

# compile
gambitc -o obj -cc-options "-D___DYNAMIC" -obj obj/uo.c obj/avr.c obj/avr.o1.c || exit

gcc -shared obj/uo.o obj/avr.o obj/avr.o1.o -o avr.o1 -luo || exit
